rootLogger.level = warn
rootLogger.appenderRef.stdout.ref = console

appender.console.type = Console
appender.console.name = console
appender.console.layout.type = PatternLayout
appender.console.layout.pattern = %d{HH:mm:ss} %-5p [%logger{1}] %msg%n

logger.spark.name = org.apache.spark
logger.spark.level = warn

logger.hadoop.name = org.apache.hadoop
logger.hadoop.level = warn

logger.netty.name = io.netty
logger.netty.level = warn

logger.delta.name = io.delta
logger.delta.level = warn

logger.parquet.name = org.apache.parquet
logger.parquet.level = warn

logger.jetty.name = org.sparkproject.jetty
logger.jetty.level = warn

logger.cornbelt.name = com.cornbelt
logger.cornbelt.level = info
